// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    name, colDefs, tagDefs, rowData
) VALUES (
    $1, $2, $3, $4
)
RETURNING name, coldefs, tagdefs, rowdata
`

type CreateAccountParams struct {
	Name    string
	Coldefs []byte
	Tagdefs []byte
	Rowdata []byte
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.Name,
		arg.Coldefs,
		arg.Tagdefs,
		arg.Rowdata,
	)
	var i Account
	err := row.Scan(
		&i.Name,
		&i.Coldefs,
		&i.Tagdefs,
		&i.Rowdata,
	)
	return i, err
}

const getAccount = `-- name: GetAccount :one
SELECT name, coldefs, tagdefs, rowdata
FROM accounts
WHERE name = $1
`

func (q *Queries) GetAccount(ctx context.Context, name string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccount, name)
	var i Account
	err := row.Scan(
		&i.Name,
		&i.Coldefs,
		&i.Tagdefs,
		&i.Rowdata,
	)
	return i, err
}

const getAccountNames = `-- name: GetAccountNames :many
SELECT name FROM accounts
`

func (q *Queries) GetAccountNames(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAccountNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT name, coldefs, tagdefs, rowdata FROM accounts
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.Query(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.Name,
			&i.Coldefs,
			&i.Tagdefs,
			&i.Rowdata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
